name: Publish

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  PROTOC_VERSION: 3

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@${{ env.PROTOC_VERSION }}
      - run: cargo version && rustc -V
      - run: cargo build --workspace --all-features
      - run: cargo publish -p tonic-codec-protobuf
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.TONIC_PROTOBUF_RELEASE_TOKEN }}
      - run: cargo publish -p tonic-build-protobuf
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.TONIC_PROTOBUF_RELEASE_TOKEN }}
